FROM node:alpine

WORKDIR /api-bobobox

COPY package.json package-lock.json ./

RUN npm install --production

RUN npm i -g pm2

COPY . .

EXPOSE 3000

CMD ["pm2", "start", "process.json", "--no-daemon"]